server:
  port: 8081
  servlet:
    context-path: /payment-service

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

message:
  payment-queue: paymentQueue
  food-delivery-routing-key: message.fds
  payment-routing-key: message.payment